services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mony
      POSTGRES_USER: mony
      POSTGRES_PASSWORD: mony
    ports:
      - "5432:5432"
    volumes:
      - mony-postgres:/var/lib/postgresql/data

volumes:
  mony-postgres:
